# Go 语言中输出错误信息的多种方式

## 对比

| 函数名          | 描述                                                           | 示例                                                        |
| ------------ | ------------------------------------------------------------ | --------------------------------------------------------- |
| `fmt.Printf` | 格式化打印信息，但不会终止程序。适用于需要输出调试信息或日志信息的场景。                         | `fmt.Printf("数据库查询错误: %s\n", err)`                        |
| `log.Fatalf` | 格式化打印错误信息，并立即终止程序的执行。适用于遇到不可恢复的错误时。                          | `log.Fatalf("数据库查询错误: %s", err)`                          |
| `panic`      | 停止当前函数的执行，然后逐层向上执行每一层函数的 defer，然后终止程序。适用于遇到严重错误，需要立即停止程序的场景。 | `panic("数据库查询错误: " + err.Error())`                        |
| `fmt.Errorf` |  `fmt.Errorf` 不会终止程序。它只是创建一个新的错误对象，并返回这个错误对象，供调用者处理。         | `newErr := fmt.Errorf("数据库查询错误: %w", err); return newErr` |

## 额外说明

* `panic`：当 panic 被调用时，它会立即停止当前函数的执行，并开始逐层向上执行每一层函数的 defer，然后终止程序。这个过程被称为“恐慌”过程。在恐慌过程中，程序会打印出调用栈的信息，这对于调试是非常有用的。  
* `log.Fatalf`：这个函数会打印出格式化的错误信息，然后调用 os.Exit(1) 来终止程序的运行。所以，当你在代码中使用 log.Fatalf 时，如果这行代码被执行，那么你的程序将会被立即终止，且不会执行任何 defer 语句。